"""Stable, low-token Gemini analysis for authenticated finance dashboard data."""

import hashlib
import json
import os
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal, ROUND_HALF_UP
from typing import Annotated, Any

from google import genai
from google.genai import types
from pydantic import BaseModel, Field, ValidationError
import tiktoken

from app.prompts.transaction_analysis import PROMPT_VERSION, build_transaction_analysis_prompt


DEFAULT_GEMINI_MODEL = "gemini-3.5-flash-lite"
MONEY_QUANTUM = Decimal("0.01")
MAX_TOP_EXPENSES = 5
NarrativeItem = Annotated[str, Field(min_length=1, max_length=140)]


class GeminiAnalysisError(RuntimeError):
    """Raised when Gemini cannot produce a safe, valid dashboard analysis."""


class ExpenseSubcategoryResponse(BaseModel):
    category: str = Field(min_length=1, max_length=200)
    amount: Decimal = Field(ge=0, max_digits=12, decimal_places=2)


class ExpenseCategoryResponse(BaseModel):
    category: str = Field(min_length=1, max_length=200)
    amount: Decimal = Field(ge=0, max_digits=12, decimal_places=2)
    subcategories: list[ExpenseSubcategoryResponse] = Field(max_length=50)


class TransactionAnalysisResponse(BaseModel):
    summary: str = Field(min_length=1, max_length=280)
    expense_categories: list[ExpenseCategoryResponse] = Field(max_length=50)
    risks: list[NarrativeItem] = Field(max_length=3)
    recommendations: list[NarrativeItem] = Field(max_length=3)
    cached: bool = False
    generated_at: datetime | None = None


class GeminiTransactionAnalysis(BaseModel):
    """Only the narrative fields generated by Gemini; amounts stay on the backend."""

    summary: str = Field(min_length=1, max_length=280)
    risks: list[NarrativeItem] = Field(max_length=3)
    recommendations: list[NarrativeItem] = Field(max_length=3)


@dataclass(frozen=True)
class PreparedTransactionAnalysis:
    """Compact backend facts and the cache key for one ledger state."""

    facts: dict[str, Any]
    expense_totals: dict[str, dict[str, Decimal]]
    ledger_hash: str
    is_sufficient: bool


@dataclass(frozen=True)
class GeminiUsage:
    """Provider-reported token usage, safe to persist as optional metrics."""

    input_tokens: int | None = None
    output_tokens: int | None = None
    thought_tokens: int | None = None
    cached_tokens: int | None = None


@dataclass(frozen=True)
class GeminiCallResult:
    analysis: GeminiTransactionAnalysis
    usage: GeminiUsage
    model: str


@dataclass(frozen=True)
class TokenEstimate:
    """Local token estimate; Gemini billing remains authoritative."""

    input_tokens: int
    output_token_budget: int
    potential_total_tokens: int
    tokenizer: str = "cl100k_base"


def _format_category(transaction: dict[str, object]) -> str:
    main_category = transaction.get("main_category")
    subcategory = str(transaction["subcategory"])
    return f"{main_category} → {subcategory}" if main_category else subcategory


def _expense_totals(transactions: list[dict[str, object]]) -> dict[str, dict[str, Decimal]]:
    """Return expense totals grouped as main category → subcategory."""
    totals: defaultdict[str, defaultdict[str, Decimal]] = defaultdict(lambda: defaultdict(Decimal))
    for transaction in transactions:
        if transaction["transaction_type"] == "expense":
            main_category = str(transaction.get("main_category") or "Без основної категорії")
            subcategory = str(transaction["subcategory"])
            totals[main_category][subcategory] += Decimal(str(transaction["amount"]))
    return {
        main_category: {
            subcategory: amount.quantize(MONEY_QUANTUM, rounding=ROUND_HALF_UP)
            for subcategory, amount in sorted(subcategories.items(), key=lambda item: (-item[1], item[0]))
        }
        for main_category, subcategories in sorted(
            totals.items(),
            key=lambda item: (-sum(item[1].values(), Decimal()), item[0]),
        )
    }


def _transaction_date(transaction: dict[str, object]) -> str:
    created_at = transaction["created_at"]
    return created_at.date().isoformat() if isinstance(created_at, datetime) else str(created_at)[:10]


def _money(value: Decimal) -> str:
    return f"{value.quantize(MONEY_QUANTUM, rounding=ROUND_HALF_UP):.2f}"


def _build_signals(
    expense_totals: dict[str, dict[str, Decimal]],
    top_expenses: list[dict[str, str]],
    total_expense: Decimal,
) -> list[dict[str, str]]:
    """Calculate transparent, deterministic signals before asking the model."""
    if not total_expense:
        return []

    signals: list[dict[str, str]] = []
    if top_expenses:
        largest = Decimal(top_expenses[0]["amount"])
        share = largest / total_expense
        if share >= Decimal("0.35"):
            signals.append(
                {
                    "type": "large_single_expense",
                    "message": "Одна витрата становить значну частку всіх витрат.",
                }
            )

    if expense_totals:
        largest_category, subcategories = next(iter(expense_totals.items()))
        largest_category_amount = sum(subcategories.values(), Decimal())
        category_share = largest_category_amount / total_expense
        if category_share >= Decimal("0.50"):
            signals.append(
                {
                    "type": "category_concentration",
                    "message": f"Витрати суттєво зосереджені в категорії «{largest_category}».",
                }
            )
    return signals


def prepare_transaction_analysis(
    transactions: list[dict[str, object]],
) -> PreparedTransactionAnalysis:
    """Aggregate raw transactions into the minimal factual payload sent to Gemini."""
    expense_totals = _expense_totals(transactions)
    expenses = [
        transaction
        for transaction in transactions
        if transaction["transaction_type"] == "expense"
    ]
    total_expense = sum(
        (amount for subcategories in expense_totals.values() for amount in subcategories.values()),
        Decimal(),
    )
    total_income = sum(
        (Decimal(str(transaction["amount"])) for transaction in transactions if transaction["transaction_type"] == "income"),
        Decimal(),
    )
    top_expenses = [
        {
            "date": _transaction_date(transaction),
            "category": _format_category(transaction),
            "amount": _money(Decimal(str(transaction["amount"]))),
            "description": str(transaction.get("description") or "").strip()[:120],
        }
        for transaction in sorted(
            expenses,
            key=lambda transaction: (
                -Decimal(str(transaction["amount"])),
                _transaction_date(transaction),
                int(transaction.get("id") or 0),
            ),
        )[:MAX_TOP_EXPENSES]
    ]
    dates = sorted(_transaction_date(transaction) for transaction in transactions)
    is_sufficient = len(expenses) >= 3 and total_expense > 0
    facts: dict[str, Any] = {
        "data_sufficiency": "sufficient" if is_sufficient else "insufficient",
        "period": {"from": dates[0] if dates else None, "to": dates[-1] if dates else None},
        "transaction_count": len(transactions),
        "expense_count": len(expenses),
        "total_income": _money(total_income),
        "total_expense": _money(total_expense),
        "expense_categories": [
            {
                "category": main_category,
                "amount": _money(sum(subcategories.values(), Decimal())),
                "subcategories": [
                    {"category": subcategory, "amount": _money(amount)}
                    for subcategory, amount in subcategories.items()
                ],
            }
            for main_category, subcategories in expense_totals.items()
        ],
        "top_expenses": top_expenses,
        "signals": _build_signals(expense_totals, top_expenses, total_expense),
    }
    canonical_facts = json.dumps(facts, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    ledger_hash = hashlib.sha256(
        f"{PROMPT_VERSION}:{canonical_facts}".encode("utf-8")
    ).hexdigest()
    return PreparedTransactionAnalysis(
        facts=facts,
        expense_totals=expense_totals,
        ledger_hash=ledger_hash,
        is_sufficient=is_sufficient,
    )


def insufficient_data_analysis() -> GeminiTransactionAnalysis:
    """Avoid an unnecessary LLM call when a ledger cannot support an analysis."""
    return GeminiTransactionAnalysis(
        summary="Недостатньо даних про витрати для надійного фінансового аналізу.",
        risks=[],
        recommendations=[],
    )


def _normalise_analysis(analysis: GeminiTransactionAnalysis) -> GeminiTransactionAnalysis:
    def clean(items: list[str]) -> list[str]:
        unique_items: list[str] = []
        seen: set[str] = set()
        for item in items:
            normalized = item.strip()
            key = normalized.casefold()
            if normalized and key not in seen:
                seen.add(key)
                unique_items.append(normalized)
        return unique_items

    summary = analysis.summary.strip()
    if not summary:
        raise GeminiAnalysisError("Gemini returned an empty summary.")
    return GeminiTransactionAnalysis(
        summary=summary,
        risks=clean(analysis.risks),
        recommendations=clean(analysis.recommendations),
    )


def build_dashboard_analysis(
    analysis: GeminiTransactionAnalysis,
    prepared: PreparedTransactionAnalysis,
) -> TransactionAnalysisResponse:
    """Attach backend-calculated category totals to validated Gemini narrative."""
    normalized_analysis = _normalise_analysis(analysis)
    return TransactionAnalysisResponse(
        summary=normalized_analysis.summary,
        expense_categories=[
            ExpenseCategoryResponse(
                category=main_category,
                amount=sum(subcategories.values(), Decimal()),
                subcategories=[
                    ExpenseSubcategoryResponse(category=subcategory, amount=amount)
                    for subcategory, amount in subcategories.items()
                ],
            )
            for main_category, subcategories in prepared.expense_totals.items()
        ],
        risks=normalized_analysis.risks,
        recommendations=normalized_analysis.recommendations,
    )


def _optional_int(value: object) -> int | None:
    return int(value) if value is not None else None


def _read_float_setting(name: str, default: float) -> float:
    try:
        return float(os.getenv(name, str(default)))
    except ValueError:
        return default


def _read_int_setting(name: str, default: int) -> int:
    try:
        return int(os.getenv(name, str(default)))
    except ValueError:
        return default


def estimate_prepared_analysis_tokens(prepared: PreparedTransactionAnalysis) -> TokenEstimate:
    """Estimate the prompt and configured output budget without calling Gemini."""
    prompt = build_transaction_analysis_prompt(prepared.facts)
    input_tokens = len(tiktoken.get_encoding("cl100k_base").encode(prompt))
    output_token_budget = _read_int_setting("GEMINI_MAX_OUTPUT_TOKENS", 700)
    return TokenEstimate(
        input_tokens=input_tokens,
        output_token_budget=output_token_budget,
        potential_total_tokens=input_tokens + output_token_budget,
    )


def analyze_prepared_transactions_with_gemini(
    prepared: PreparedTransactionAnalysis,
) -> GeminiCallResult:
    """Call Gemini once with compact facts, deterministic settings, and structured output."""
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise GeminiAnalysisError("GEMINI_API_KEY is not configured.")

    model = os.getenv("GEMINI_MODEL", DEFAULT_GEMINI_MODEL)
    thinking_level = os.getenv("GEMINI_THINKING_LEVEL", "low").strip().lower()
    config_values: dict[str, object] = {
        "response_mime_type": "application/json",
        "response_schema": GeminiTransactionAnalysis,
        "temperature": _read_float_setting("GEMINI_TEMPERATURE", 0.1),
        "max_output_tokens": _read_int_setting("GEMINI_MAX_OUTPUT_TOKENS", 700),
        "seed": _read_int_setting("GEMINI_SEED", 42),
    }
    if thinking_level:
        config_values["thinking_config"] = types.ThinkingConfig(thinking_level=thinking_level)

    try:
        client = genai.Client(api_key=api_key)
        response = client.models.generate_content(
            model=model,
            contents=build_transaction_analysis_prompt(prepared.facts),
            config=types.GenerateContentConfig(**config_values),
        )
        if not response.text:
            raise GeminiAnalysisError("Gemini returned an empty response.")
        analysis = GeminiTransactionAnalysis.model_validate_json(response.text)
    except ValidationError as error:
        raise GeminiAnalysisError("Gemini returned an invalid structured response.") from error
    except GeminiAnalysisError:
        raise
    except Exception as error:
        raise GeminiAnalysisError("Gemini request failed.") from error

    usage_metadata = response.usage_metadata
    usage = GeminiUsage(
        input_tokens=_optional_int(getattr(usage_metadata, "prompt_token_count", None)),
        output_tokens=_optional_int(getattr(usage_metadata, "candidates_token_count", None)),
        thought_tokens=_optional_int(getattr(usage_metadata, "thoughts_token_count", None)),
        cached_tokens=_optional_int(getattr(usage_metadata, "cached_content_token_count", None)),
    )
    return GeminiCallResult(analysis=_normalise_analysis(analysis), usage=usage, model=model)
